#!/bin/sh
# Convinience script for puavo-ca-rails db migrations

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

export RAILS_ENV=production
cd /var/app/puavo-ca-rails
sudo -E -u puavoca bundle exec rake db:migrate
