#!/bin/sh

set -e

rm -f /opt/processing/java

javalink_ok=false

for javadir in /opt/java/jre* /opt/java/jdk*; do
  if [ -d "$javadir" ]; then
    ln -fns "$javadir" /opt/processing/java
    javalink_ok=true
  fi
done

if ! $javalink_ok; then
  exit 1
fi
