# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /home/kaze/Documents/KompoZer/svn/trunk/mozilla/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/home/kaze/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
MOZ_OBJDIR=$(TOPSRCDIR)/../obj-$(CONFIG_GUESS)
# --enable-application=composer is used by configure (not client.mk)
# --enable-optimize is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --enable-xpfe-components is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --disable-installer is used by configure (not client.mk)
# --enable-extensions=default spellcheck is used by configure (not client.mk)
# --enable-necko-protocols=http,ftp,file,jar,viewsource,res,data is used by configure (not client.mk)
# --enable-default-toolkit=gtk2 is used by configure (not client.mk)
# --enable-xft is used by configure (not client.mk)
# --enable-pango is used by configure (not client.mk)
# --enable-postscript is used by configure (not client.mk)
# --disable-xprint is used by configure (not client.mk)
# --enable-mathml is used by configure (not client.mk)
# --enable-svg is used by configure (not client.mk)
# --enable-svg-renderer=cairo is used by configure (not client.mk)
# --enable-system-cairo is used by configure (not client.mk)
# --enable-canvas is used by configure (not client.mk)
# --with-system-png=/usr is used by configure (not client.mk)
# --with-system-jpeg=/usr is used by configure (not client.mk)
# --with-system-zlib=/usr is used by configure (not client.mk)
# --enable-gnomevfs is used by configure (not client.mk)
# --enable-xinerama is used by configure (not client.mk)
# --enable-single-profile is used by configure (not client.mk)
# --disable-profilesharing is used by configure (not client.mk)
# --enable-system-myspell is used by configure (not client.mk)
