#!/bin/sh

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

version=jdk1.7.0_21

update-alternatives --remove \
  mozilla-javaplugin.so \
  /usr/lib/mozilla/plugins/libjavaplugin.so

update-alternatives --remove \
  javaws \
  /usr/bin/javaws
