#!/bin/sh

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

version=jdk1.7.0_21

update-alternatives --remove \
  /usr/lib/mozilla/plugins/libjavaplugin.so \
  mozilla-javaplugin.so

update-alternatives --remove \
  /usr/bin/javaws \
  javaws
