#!/bin/sh

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin

version=jdk1.7.0_67

update-alternatives --remove \
  mozilla-javaplugin.so \
  /opt/java/${version}/jre/lib/i386/libnpjp2.so

update-alternatives --remove \
  javaws \
  /opt/java/${version}/bin/javaws \
